kibana:
  url: "https://kibana.test"
  api_key: "kibana-api-key" # Requires all privileges for the Cases feature in the Management, Observability, or Security section 
  verify_ssl: True # Set to false if using self signed certs

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"