kibana:
  url: "https://kibana.test"
  api_key: "kibana-api-key" # Requires all privileges for the Cases feature in the Management, Observability, or Security section 
  verify_ssl: True # Set to false if using self signed certs
  search_tag: "search"
  search_interval: 60 # Interval in seconds

gitea:
  url: "https://gitea.test"
  api_key: "gitea-api-key" # API key needs read and write access to issues, and read access to orgs
  organization: "gitea-org"
  issue_repo: "gitea-repo"
  label-ids: # IDs of the Gitea labels corresponding to the Kibana case severity
    severity:
      low: 13
      medium: 12
      high: 11
      critical: 10

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"